# coding: utf-8 -*-
import os ,time
#####################
vpstime = time.time()
#####################
print("歡迎使用VPS環境安裝包\n即將開始為您安裝伺服器環境")
os.system("sudo apt update -y")
print("apt 系統更新完畢")
os.system("sudo apt install python-pip -y")
os.system("sudo apt install python3-pip -y")
print("pip 安裝完畢")
print("正在開始安裝py套件")
time.sleep(2)
os.system("sudo pip install --upgrade pip -y")
os.system("sudo pip3 install --upgrade pip -y")
print("PIP 更新完畢")
os.system("pip3 install rsa")
print("rsa安裝完畢")
os.system("pip3 install thrift==0.11.0")
print("thrift安裝完畢")
os.system("pip3 install requests")
print("requests安裝完畢")
os.system("pip3 install pytz")
print("pytz安裝完畢")
os.system("pip3 install bs4")
print("bs4安裝完畢")
os.system("pip3 install googletrans")
print("googletrans安裝完畢")
os.system("pip3 install youtube_dl")
print("yt_dl安裝完畢")
os.system("pip3 install pafy")
print("pafy安裝完畢")
os.system("pip3 install humanfriendly")
print("humanfriendly安裝完畢")
os.system("pip3 install asyncio")
print("asyncio安裝完畢")
os.system("pip3 install humanize")
print("humanize安裝完成")
os.system("pip3 install paramiko")
print("paramiko安裝完成")
os.system("pip3 install hyper")
print("hyper安裝完成")
os.system("pip3 install speedtest -y")
os.system("sudo apt install speedtest-cli")
print("speedtest安裝完成")
os.system("pip3 install twder")
print("twder安裝完成")
os.system("pip3 install httplib2")
print("httplib2安裝完成")
os.system("pip3 install python-axolotl-curve25519")
print("axolotl-curve25519 安裝完成")
os.system("pip3 install requests_futures")
print("requests_futures 安裝完成")
os.system("pip3 install pycryptodome")
print("pycryptodome 安裝完成")
os.system("pip3 install CHRLINE")
print("CHRLINE 安裝完成")
os.system("sudo ln -sf /usr/share/zoneinfo/Asia/Taipei /etc/localtime")
print("時間設定完成")
os.system("sudo apt upgrade -y")
print("apt資源更新完成")
time.sleep(0.5)
print("VPS環境安裝完成 花費時間:{time}".format(time=(time.time() - vpstime)))
print("提醒您 安裝完環境請重啟VPS以正常運作")
